
service: cold-start-benchmarker
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 100
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "lambda:UpdateFunctionConfiguration"
          Resource: '*' # okay this should be stricter, maybe limit it to function names?

functions:
  invoke:
    handler: handler.invoke
    environment:
      FUNCTION_NAMES: ''
    events:
      - schedule: rate(1 minute)
      


